"""
data_preprocessing.py
---------------------
Prepares training and test CSVs from available data sources.

Data sources (merged in order):
  1. Local Fake.csv / True.csv  (always loaded)
  2. LIAR dataset from HuggingFace  (--liar flag)
  3. Synthetic data from generate_training_data.py  (--synthetic PATH)

Label schema:
  0 = Highly Deceptive  (conspiracy-style fake news, pants-fire lies)
  1 = Misleading        (political/general fake news, half-truths, exaggerated framing)
  2 = Legitimate        (true news, credible reporting, well-sourced statements)

Usage:
  python src/data_preprocessing.py                          # local data only
  python src/data_preprocessing.py --liar                   # + LIAR dataset
  python src/data_preprocessing.py --synthetic src/synthetic_data.csv
  python src/data_preprocessing.py --liar --synthetic src/synthetic_data.csv
"""

import argparse
import os

import pandas as pd
from sklearn.model_selection import train_test_split


def load_local_data():
    """Load the local Fake.csv / True.csv files and assign 3-class labels."""
    fake = pd.read_csv("src/Fake.csv")
    true = pd.read_csv("src/True.csv")

    fake["text"] = (fake["title"] + " " + fake["text"]).str.strip()
    true["text"] = (true["title"] + " " + true["text"]).str.strip()

    # Label assignment based on subject category:
    # Government/Middle-east fake articles → most conspiratorial → 0 (Highly Deceptive)
    # All other fake articles              → political exaggeration → 1 (Misleading)
    # All true articles                    → credible reporting   → 2 (Legitimate)
    highly  = fake[fake["subject"].isin(["Government News", "Middle-east"])].copy()
    highly["label"] = 0

    partial = fake[~fake.index.isin(highly.index)].copy()
    partial["label"] = 1

    true["label"] = 2

    data = pd.concat([highly, partial, true], ignore_index=True)
    print(f"Local dataset: {len(data)} samples")
    return data[["text", "label"]]


def load_liar_dataset():
    """
    Download the LIAR dataset (12,836 fact-checked political statements) and map
    its 6 PolitiFact ratings to our 3-class schema.

    Downloads parquet files directly from HuggingFace CDN — no loading script needed.

    LIAR int label → our label:
      0 (false),      5 (pants-fire)  → 0  Highly Deceptive
      2 (barely-true),3 (half-true)   → 1  Misleading
      4 (mostly-true),1 (true)        → 2  Legitimate
    """
    try:
        import io
        import requests as req
    except ImportError:
        print("[WARN] requests not installed. Run: pip install requests")
        return None

    # Direct parquet CDN — no HuggingFace datasets library needed
    BASE = (
        "https://huggingface.co/datasets/liar"
        "/resolve/refs%2Fconvert%2Fparquet/default/"
    )
    SPLITS = {
        "train":      "train/0000.parquet",
        "validation": "validation/0000.parquet",
        "test":       "test/0000.parquet",
    }
    # Verified mapping: 0=false,1=true,2=barely-true,3=half-true,4=mostly-true,5=pants-fire
    INT_MAP = {0: 0, 5: 0, 2: 1, 3: 1, 4: 2, 1: 2}

    print("\n[LIAR] Downloading parquet files from HuggingFace CDN...")
    dfs = []
    for split, path in SPLITS.items():
        try:
            resp = req.get(BASE + path, timeout=60)
            resp.raise_for_status()
            df_split = pd.read_parquet(io.BytesIO(resp.content))
            dfs.append(df_split)
            print(f"  {split}: {len(df_split)} rows")
        except Exception as exc:
            print(f"  {split}: FAILED — {exc}")

    if not dfs:
        print("[WARN] All LIAR downloads failed — skipping.")
        return None

    raw = pd.concat(dfs, ignore_index=True)

    rows = []
    for _, row in raw.iterrows():
        text   = str(row.get("statement", "")).strip()
        mapped = INT_MAP.get(int(row["label"])) if pd.notna(row.get("label")) else None
        if mapped is not None and len(text) >= 10:
            rows.append({"text": text, "label": mapped})

    df = pd.DataFrame(rows)
    print(f"[LIAR] {len(df)} statements loaded. Label distribution:")
    for lbl, name in enumerate(["Highly Deceptive", "Misleading", "Legitimate"]):
        print(f"  {lbl} ({name}): {(df['label']==lbl).sum()}")
    return df[["text", "label"]]


def load_synthetic_data(path):
    """Load synthetic training data generated by generate_training_data.py."""
    if not os.path.exists(path):
        print(f"[WARN] Synthetic data file not found: {path}")
        return None

    df = pd.read_csv(path).dropna(subset=["text", "label"])
    df["label"] = df["label"].astype(int)
    df = df[df["label"].isin([0, 1, 2])][["text", "label"]].reset_index(drop=True)
    print(f"[Synthetic] {len(df)} samples loaded from {path}")
    return df


def balance_dataset(data: pd.DataFrame, target_per_class: int = None,
                    strategy: str = "undersample",
                    max_oversample_ratio: float = 2.0) -> pd.DataFrame:
    """
    Balance all three label classes to equal counts.

    strategy='undersample': cap every class to the minority count — zero duplication,
                            all minority samples used, majority samples randomly dropped.
    strategy='oversample' : upsample minority classes, capped at max_oversample_ratio ×
                            the natural class count to prevent excessive memorisation.
    strategy='median'     : target the median class count.

    max_oversample_ratio: when oversampling, no class will be repeated more than this
                          many times its original size (default 2.0 = at most 2× copies).
                          Ignored for undersample/median strategies.
    """
    from sklearn.utils import resample

    counts = {lbl: int((data["label"] == lbl).sum()) for lbl in [0, 1, 2]}
    print("\nClass counts before balancing:")
    for lbl, name in enumerate(["Highly Deceptive", "Misleading", "Legitimate"]):
        print(f"  {lbl} ({name}): {counts[lbl]}")

    non_zero = [c for c in counts.values() if c > 0]
    if target_per_class is not None:
        target = target_per_class
    elif strategy == "undersample":
        target = min(non_zero)
    elif strategy == "oversample":
        # Desired target = majority count, but capped at max_oversample_ratio × each
        # class's own size so no class is repeated excessively.
        desired = max(non_zero)
        target  = desired   # will be capped per-class below
    else:  # median
        target = int(sorted(non_zero)[len(non_zero) // 2])

    print(f"Balance strategy: {strategy}  |  Target per class: {target}"
          + (f"  |  Max oversample ratio: {max_oversample_ratio}×" if strategy == "oversample" else ""))
    parts = []
    for lbl in [0, 1, 2]:
        grp = data[data["label"] == lbl]
        if len(grp) == 0:
            continue
        if len(grp) < target:
            # Cap oversampling so we never repeat a class more than max_oversample_ratio×
            capped_target = int(min(target, len(grp) * max_oversample_ratio))
            if capped_target < target:
                print(f"  [CAP] Label {lbl}: capped at {capped_target} "
                      f"({max_oversample_ratio}× of {len(grp)} natural samples)")
            grp = resample(grp, replace=True, n_samples=capped_target, random_state=42)
        elif len(grp) > target:
            grp = grp.sample(target, random_state=42)
        parts.append(grp)

    balanced = pd.concat(parts, ignore_index=True).sample(frac=1, random_state=42)
    print("Class counts after balancing:")
    for lbl, name in enumerate(["Highly Deceptive", "Misleading", "Legitimate"]):
        print(f"  {lbl} ({name}): {(balanced['label'] == lbl).sum()}")
    return balanced.reset_index(drop=True)


def load_live_news(path: str = "src/live_news.csv") -> pd.DataFrame:
    """Load accumulated live_news.csv to supplement initial training data."""
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path).dropna(subset=["text", "label"])
    df["label"] = df["label"].astype(int)
    df = df[df["label"].isin([0, 1, 2])][["text", "label"]].reset_index(drop=True)
    print(f"[Live News] {len(df)} samples loaded from {path}")
    return df


def main():
    parser = argparse.ArgumentParser(description="Preprocess training data for Veritas AI")
    parser.add_argument("--liar",             action="store_true", help="Download and merge the LIAR dataset from HuggingFace")
    parser.add_argument("--synthetic",        default=None,        help="Path to synthetic_data.csv from generate_training_data.py")
    parser.add_argument("--live-news",        default=None,        help="Path to live_news.csv to merge into training data (use 'auto' for src/live_news.csv)")
    parser.add_argument("--extra",            action="append",     default=[], metavar="PATH", help="Extra CSV file(s) with text+label columns to merge (can be repeated)")
    parser.add_argument("--test-size",        type=float, default=0.2, help="Fraction of data held out for testing (default 0.2)")
    parser.add_argument("--balance",          dest="balance", action="store_true",  default=True, help="Equalize class counts after merging (default: enabled)")
    parser.add_argument("--no-balance",       dest="balance", action="store_false", help="Disable class balancing")
    parser.add_argument("--balance-strategy", default="undersample",                choices=["undersample", "oversample", "median"],
                        help="undersample=cap all to minority count (no duplication); oversample=upsample minority; median=target median count. Default: undersample")
    parser.add_argument("--target-per-class",      type=int,   default=None,        help="Override target samples per class when balancing")
    parser.add_argument("--max-oversample-ratio",  type=float, default=2.0,         help="Max repetition multiplier when oversampling (default 2.0 = at most 2× copies). Prevents memorisation.")
    args = parser.parse_args()

    # 1. Local data
    data = load_local_data()

    # 2. LIAR dataset (optional)
    if args.liar:
        liar_df = load_liar_dataset()
        if liar_df is not None:
            data = pd.concat([data, liar_df], ignore_index=True)
            print(f"After merging LIAR: {len(data)} total samples")

    # 3. Synthetic data (optional)
    if args.synthetic:
        syn_df = load_synthetic_data(args.synthetic)
        if syn_df is not None:
            data = pd.concat([data, syn_df], ignore_index=True)
            print(f"After merging synthetic: {len(data)} total samples")

    # 4. Extra CSV files (optional) — any additional labelled datasets
    for extra_path in args.extra:
        if os.path.exists(extra_path):
            extra_df = pd.read_csv(extra_path).dropna(subset=["text", "label"])
            extra_df["label"] = extra_df["label"].astype(int)
            extra_df = extra_df[extra_df["label"].isin([0, 1, 2])][["text", "label"]].reset_index(drop=True)
            data = pd.concat([data, extra_df], ignore_index=True)
            print(f"[Extra] {len(extra_df)} samples loaded from {extra_path}. Total: {len(data)}")
        else:
            print(f"[WARN] Extra file not found: {extra_path}")

    # 5. Live news (optional) — use accumulated live_news.csv to include
    #    recent 2022-today articles without re-scraping datasets
    live_path = "src/live_news.csv" if args.live_news == "auto" else args.live_news
    if live_path:
        live_df = load_live_news(live_path)
        if live_df is not None:
            data = pd.concat([data, live_df], ignore_index=True)
            print(f"After merging live news: {len(data)} total samples")

    # Deduplicate and shuffle
    data["text"] = data["text"].astype(str).str.strip()
    before = len(data)
    data = data.drop_duplicates(subset=["text"]).reset_index(drop=True)
    if before != len(data):
        print(f"Removed {before - len(data)} duplicate entries.")

    # 5. Class balancing — ensures no single label dominates the training set
    counts = [int((data["label"] == lbl).sum()) for lbl in [0, 1, 2]]
    ratio = max(counts) / max(min(counts), 1)
    if ratio > 2.0 and not args.balance:
        print(f"\n[WARN] Class imbalance ratio {ratio:.1f}× detected. "
              "Use --balance to equalize (recommended).")

    if args.balance:
        data = balance_dataset(data, target_per_class=args.target_per_class,
                               strategy=args.balance_strategy,
                               max_oversample_ratio=args.max_oversample_ratio)

    data = data.sample(frac=1, random_state=42).reset_index(drop=True)

    print("\nFinal label distribution:")
    for label, name in enumerate(["Highly Deceptive", "Misleading", "Legitimate"]):
        count = (data["label"] == label).sum()
        print(f"  {label} ({name}): {count}")

    # Train / test split
    train, test = train_test_split(
        data, test_size=args.test_size, stratify=data["label"], random_state=42
    )

    train.to_csv("src/train_data.csv", index=False)
    test.to_csv("src/test_data.csv",   index=False)

    print(f"\nPreprocessing complete.")
    print(f"Train : {len(train)} samples  ->  src/train_data.csv")
    print(f"Test  : {len(test)} samples   ->  src/test_data.csv")
    print("\nNext step: python src/train_model.py")


if __name__ == "__main__":
    main()
